# Generated by Django 6.0.6 on 2026-09-01 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0010_alter_opportunityfield_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gamification',
                'verbose_name_plural': 'gamification',
                'db_table': 'gamification_gamificationmodel',
            },
        ),
        migrations.CreateModel(
            name='UserViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='opportunities.opportunitymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user view',
                'verbose_name_plural': 'user views',
                'db_table': 'gamification_userviewmodel',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'opportunity'), name='unique_user_opportunity_view')],
            },
        ),
    ]
