# Generated by Django 6.0.6 on 2026-08-18 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0002_opportunitymodel_apply_clicks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedOpportunityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_by', to='opportunities.opportunitymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'applied opportunity',
                'verbose_name_plural': 'applied opportunities',
                'db_table': 'applied_appliedopportunity',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'opportunity'), name='unique_applied_per_user_opportunity')],
            },
        ),
    ]
