# Generated by Django 6.0.6 on 2026-08-17 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('volunteer', 'Volunteering'), ('competition', 'Competitions'), ('fellowship', 'Fellowships'), ('internship', 'Internships'), ('course', 'Courses'), ('workshop', 'Workshops'), ('session', 'Sessions'), ('conference', 'Conferences')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('in-person', 'In-person'), ('hybrid', 'Hybrid')], default='online', max_length=16)),
                ('duration', models.CharField(blank=True, max_length=64)),
                ('funding', models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], default='free', max_length=16)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('apply_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('age', models.CharField(choices=[('all', 'All ages'), ('13-15', '13-15'), ('15-18', '15-18'), ('+18', '+18')], default='all', max_length=16)),
                ('certificate', models.BooleanField(default=False)),
                ('seed_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'opportunity',
                'verbose_name_plural': 'opportunities',
                'db_table': 'opportunities_opportunity',
                'ordering': ['-created_at'],
            },
        ),
    ]
