# Generated by Django 6.0.6 on 2026-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymodel',
            name='apply_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
