# Generated by Django 6.0.6 on 2026-08-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunitymodel_apply_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('label_en', models.CharField(max_length=64)),
                ('label_ar', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'opportunity field',
                'verbose_name_plural': 'opportunity fields',
                'db_table': 'opportunities_opportunityfield',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='opportunitymodel',
            name='fields',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='opportunities.opportunityfield'),
        ),
    ]
