# Generated by Django 6.0.6 on 2026-08-29 16:07

from django.db import migrations, models


def backfill_status(apps, schema_editor):
    OpportunityModel = apps.get_model("opportunities", "OpportunityModel")
    OpportunityModel.objects.filter(is_active=True).update(status="published")
    OpportunityModel.objects.filter(is_active=False).update(status="hidden")


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0004_seed_opportunity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunitymodel",
            name="status",
            field=models.CharField(choices=[("published", "Published"), ("hidden", "Hidden")], default="published", max_length=16),
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
