# Generated by Django 6.0.6 on 2026-08-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_organization_adminapplication_position_and_more'),
        ('opportunities', '0005_opportunitymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymodel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='opportunitymodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden'), ('archived', 'Archived')], default='published', max_length=16),
        ),
    ]
