# Generated by Django 6.0.6 on 2026-08-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_opportunitymodel_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
