# Generated by Django 6.0.6 on 2026-09-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0009_subjectfield_hierarchy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunityfield',
            options={'ordering': ['sort_order', 'key'], 'verbose_name': 'opportunity field', 'verbose_name_plural': 'opportunity fields'},
        ),
    ]
