# Generated by Django 6.0.6 on 2026-09-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0012_general_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymodel',
            name='price',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
