# Generated by Django 6.0.6 on 2026-09-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0015_expand_categories_and_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymodel',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunitymodel',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunitymodel',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opportunitymodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
