# Generated by Django 6.0.6 on 2026-09-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0016_opportunitymodel_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymodel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
