# Generated by Django 6.0.6 on 2026-08-17 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationStoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_stories', to='opportunities.opportunitymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'participation story',
                'verbose_name_plural': 'participation stories',
                'db_table': 'stories_participationstory',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'opportunity'), name='unique_story_per_user_opportunity')],
            },
        ),
    ]
