# Generated by Django 6.0.6 on 2026-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationstorymodel',
            name='flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='participationstorymodel',
            name='helpful',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
