# Generated by Django 6.0.6 on 2026-08-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
