# Generated by Django 6.0.6 on 2026-08-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermodel_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
