# Generated by Django 6.0.6 on 2026-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usermodel_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(default='admin_verify', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'email verification code',
                'verbose_name_plural': 'email verification codes',
                'db_table': 'accounts_email_verification_code',
                'indexes': [models.Index(fields=['email', 'purpose'], name='accounts_em_email_75fdaf_idx')],
            },
        ),
    ]
