# Generated by Django 6.0.6 on 2026-08-29 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'admin application',
                'verbose_name_plural': 'admin applications',
                'db_table': 'accounts_admin_application',
            },
        ),
        migrations.RemoveIndex(
            model_name='emailverificationcode',
            name='accounts_em_email_75fdaf_idx',
        ),
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
        migrations.AddField(
            model_name='adminapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminapplication',
            index=models.Index(fields=['status', 'created_at'], name='accounts_ad_status_0ebafb_idx'),
        ),
    ]
