# Generated by Django 6.0.6 on 2026-08-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_seeded_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'db_table': 'accounts_organization',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='adminapplication',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminapplication',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('owner', 'Owner')], default='user', max_length=16),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='members', to='accounts.organization'),
        ),
    ]
