# Generated by Django 6.0.6 on 2026-09-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_passwordresetcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='accounts_pa_email_5bd7dd_idx',
            old_name='accounts_pa_email_used_idx',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
